<?php

namespace ContainerMknqzKG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends Survos_CommandBundle_Tests_TestKernelTestDebugContainer
{
    /**
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Survos\\CommandBundle\\Controller\\CommandController::runCommand' => ['privates', '.service_locator.9VN7xXM.Survos\\CommandBundle\\Controller\\CommandController::runCommand()', 'getCommandControllerrunCommandService', true],
            'Survos\\CommandBundle\\Controller\\CommandController:runCommand' => ['privates', '.service_locator.9VN7xXM.Survos\\CommandBundle\\Controller\\CommandController::runCommand()', 'getCommandControllerrunCommandService', true],
        ], [
            'Survos\\CommandBundle\\Controller\\CommandController::runCommand' => '?',
            'Survos\\CommandBundle\\Controller\\CommandController:runCommand' => '?',
        ]));
    }
}
