<?php

namespace ContainerMknqzKG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandControllerrunCommandService extends Survos_CommandBundle_Tests_TestKernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.9VN7xXM.Survos\CommandBundle\Controller\CommandController::runCommand()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9VN7xXM.Survos\\CommandBundle\\Controller\\CommandController::runCommand()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel' => ['services', 'kernel', 'getKernelService', true],
        ], [
            'kernel' => '?',
        ]))->withContext('Survos\\CommandBundle\\Controller\\CommandController::runCommand()', $container);
    }
}
