<?php

namespace ContainerMknqzKG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDumpTranslationsCommand_LazyService extends Survos_CommandBundle_Tests_TestKernelTestDebugContainer
{
    /**
     * Gets the private '.Survos\CommandBundle\Command\DumpTranslationsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Survos\\CommandBundle\\Command\\DumpTranslationsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('survos:command:dump-as-messages', ['survos:command:dump-as-messages'], 'Dump the command descriptions as a message for file translations', false, #[\Closure(name: 'Survos\\CommandBundle\\Command\\DumpTranslationsCommand')] fn (): \Survos\CommandBundle\Command\DumpTranslationsCommand => ($container->services['Survos\\CommandBundle\\Command\\DumpTranslationsCommand'] ?? $container->load('getDumpTranslationsCommandService')));
    }
}
