<?php

namespace ContainerMknqzKG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDumpTranslationsCommandService extends Survos_CommandBundle_Tests_TestKernelTestDebugContainer
{
    /**
     * Gets the public 'Survos\CommandBundle\Command\DumpTranslationsCommand' shared autowired service.
     *
     * @return \Survos\CommandBundle\Command\DumpTranslationsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 6).'/src/Command/DumpTranslationsCommand.php';

        $container->services['Survos\\CommandBundle\\Command\\DumpTranslationsCommand'] = $instance = new \Survos\CommandBundle\Command\DumpTranslationsCommand(($container->services['kernel'] ?? $container->get('kernel', 1)), [], \dirname(__DIR__, 4));

        $instance->setName('survos:command:dump-as-messages');
        $instance->setAliases(['survos:command:dump-as-messages']);
        $instance->setDescription('Dump the command descriptions as a message for file translations');

        return $instance;
    }
}
