<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
    return;
}

require dirname(__DIR__, 5).'/vendor/autoload.php';
(require __DIR__.'/Survos_CommandBundle_Tests_TestKernelTestDebugContainer.php')->set(\ContainerMknqzKG\Survos_CommandBundle_Tests_TestKernelTestDebugContainer::class, null);
require __DIR__.'/ContainerMknqzKG/getServicesResetterService.php';
require __DIR__.'/ContainerMknqzKG/getSecrets_VaultService.php';
require __DIR__.'/ContainerMknqzKG/getSecrets_EnvVarLoaderService.php';
require __DIR__.'/ContainerMknqzKG/getPropertyAccessorService.php';
require __DIR__.'/ContainerMknqzKG/getParameterBagService.php';
require __DIR__.'/ContainerMknqzKG/getForm_TypeExtension_Form_HttpFoundationService.php';
require __DIR__.'/ContainerMknqzKG/getForm_Type_FormService.php';
require __DIR__.'/ContainerMknqzKG/getForm_Type_FileService.php';
require __DIR__.'/ContainerMknqzKG/getForm_Type_ColorService.php';
require __DIR__.'/ContainerMknqzKG/getForm_Type_ChoiceService.php';
require __DIR__.'/ContainerMknqzKG/getForm_RegistryService.php';
require __DIR__.'/ContainerMknqzKG/getForm_FactoryService.php';
require __DIR__.'/ContainerMknqzKG/getForm_ChoiceListFactory_CachedService.php';
require __DIR__.'/ContainerMknqzKG/getErrorHandler_ErrorRenderer_HtmlService.php';
require __DIR__.'/ContainerMknqzKG/getErrorControllerService.php';
require __DIR__.'/ContainerMknqzKG/getDebug_ErrorHandlerConfiguratorService.php';
require __DIR__.'/ContainerMknqzKG/getContainer_GetRoutingConditionServiceService.php';
require __DIR__.'/ContainerMknqzKG/getContainer_EnvVarProcessorsLocatorService.php';
require __DIR__.'/ContainerMknqzKG/getContainer_EnvVarProcessorService.php';
require __DIR__.'/ContainerMknqzKG/getCache_SystemClearerService.php';
require __DIR__.'/ContainerMknqzKG/getCache_SystemService.php';
require __DIR__.'/ContainerMknqzKG/getCache_GlobalClearerService.php';
require __DIR__.'/ContainerMknqzKG/getCache_AppClearerService.php';
require __DIR__.'/ContainerMknqzKG/getCache_AppService.php';
require __DIR__.'/ContainerMknqzKG/getArgumentResolver_VariadicService.php';
require __DIR__.'/ContainerMknqzKG/getArgumentResolver_SessionService.php';
require __DIR__.'/ContainerMknqzKG/getArgumentResolver_ServiceService.php';
require __DIR__.'/ContainerMknqzKG/getArgumentResolver_RequestAttributeService.php';
require __DIR__.'/ContainerMknqzKG/getArgumentResolver_RequestService.php';
require __DIR__.'/ContainerMknqzKG/getArgumentResolver_QueryParameterValueResolverService.php';
require __DIR__.'/ContainerMknqzKG/getArgumentResolver_DefaultService.php';
require __DIR__.'/ContainerMknqzKG/getArgumentResolver_DatetimeService.php';
require __DIR__.'/ContainerMknqzKG/getArgumentResolver_BackedEnumResolverService.php';
require __DIR__.'/ContainerMknqzKG/getCommandControllerService.php';
require __DIR__.'/ContainerMknqzKG/getCommandControllerrunCommandService.php';

$classes = [];
$classes[] = 'Symfony\Bundle\FrameworkBundle\FrameworkBundle';
$classes[] = 'Survos\CommandBundle\SurvosCommandBundle';
$classes[] = 'Symfony\Component\DependencyInjection\ServiceLocator';
$classes[] = 'Survos\CommandBundle\Controller\CommandController';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\BackedEnumValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\DateTimeValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\DefaultValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\QueryParameterValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestAttributeValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\SessionValueResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver\VariadicValueResolver';
$classes[] = 'Symfony\Component\Cache\Adapter\FilesystemAdapter';
$classes[] = 'Symfony\Component\Cache\Marshaller\DefaultMarshaller';
$classes[] = 'Symfony\Component\HttpKernel\CacheClearer\Psr6CacheClearer';
$classes[] = 'Symfony\Component\Cache\Adapter\AdapterInterface';
$classes[] = 'Symfony\Component\Cache\Adapter\AbstractAdapter';
$classes[] = 'Symfony\Component\DependencyInjection\EnvVarProcessor';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\CacheAttributeListener';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\DebugHandlersListener';
$classes[] = 'Symfony\Component\HttpKernel\Debug\ErrorHandlerConfigurator';
$classes[] = 'Symfony\Component\ErrorHandler\ErrorRenderer\FileLinkFormatter';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\DisallowRobotsIndexingListener';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ErrorController';
$classes[] = 'Symfony\Component\ErrorHandler\ErrorRenderer\HtmlErrorRenderer';
$classes[] = 'Symfony\Component\EventDispatcher\EventDispatcher';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\ErrorListener';
$classes[] = 'Symfony\Component\Form\ChoiceList\Factory\CachingFactoryDecorator';
$classes[] = 'Symfony\Component\Form\ChoiceList\Factory\PropertyAccessDecorator';
$classes[] = 'Symfony\Component\Form\ChoiceList\Factory\DefaultChoiceListFactory';
$classes[] = 'Symfony\Component\Form\FormFactory';
$classes[] = 'Symfony\Component\Form\FormRegistry';
$classes[] = 'Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension';
$classes[] = 'Symfony\Component\Form\ResolvedFormTypeFactory';
$classes[] = 'Symfony\Component\Form\Extension\Core\Type\ChoiceType';
$classes[] = 'Symfony\Component\Form\Extension\Core\Type\ColorType';
$classes[] = 'Symfony\Component\Form\Extension\Core\Type\FileType';
$classes[] = 'Symfony\Component\Form\Extension\Core\Type\FormType';
$classes[] = 'Symfony\Component\Form\Extension\HttpFoundation\Type\FormTypeHttpFoundationExtension';
$classes[] = 'Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequestHandler';
$classes[] = 'Symfony\Component\Form\Util\ServerParams';
$classes[] = 'Symfony\Component\Form\Extension\Core\Type\TransformationFailureExtension';
$classes[] = 'Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension';
$classes[] = 'Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension';
$classes[] = 'Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner';
$classes[] = 'Symfony\Component\Runtime\Runner\Symfony\ResponseRunner';
$classes[] = 'Symfony\Component\Runtime\SymfonyRuntime';
$classes[] = 'Symfony\Component\HttpKernel\HttpKernel';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver';
$classes[] = 'Symfony\Component\HttpKernel\Controller\ArgumentResolver';
$classes[] = 'Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactory';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\LocaleListener';
$classes[] = 'Symfony\Component\HttpKernel\Log\Logger';
$classes[] = 'Symfony\Component\DependencyInjection\ParameterBag\ContainerBag';
$classes[] = 'Symfony\Component\PropertyAccess\PropertyAccessor';
$classes[] = 'Symfony\Component\Cache\Adapter\ArrayAdapter';
$classes[] = 'Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor';
$classes[] = 'Symfony\Component\HttpFoundation\RequestStack';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\ResponseListener';
$classes[] = 'Symfony\Component\DependencyInjection\StaticEnvVarLoader';
$classes[] = 'Symfony\Bundle\FrameworkBundle\Secrets\SodiumVault';
$classes[] = 'Symfony\Component\String\LazyString';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';
$classes[] = 'Symfony\Component\HttpKernel\DependencyInjection\ServicesResetter';
$classes[] = 'Symfony\Component\HttpKernel\EventListener\ValidateRequestListener';

$preloaded = Preloader::preload($classes);
