<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMknqzKG\Survos_CommandBundle_Tests_TestKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMknqzKG/Survos_CommandBundle_Tests_TestKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerMknqzKG.legacy');

    return;
}

if (!\class_exists(Survos_CommandBundle_Tests_TestKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerMknqzKG\Survos_CommandBundle_Tests_TestKernelTestDebugContainer::class, Survos_CommandBundle_Tests_TestKernelTestDebugContainer::class, false);
}

return new \ContainerMknqzKG\Survos_CommandBundle_Tests_TestKernelTestDebugContainer([
    'container.build_hash' => 'MknqzKG',
    'container.build_id' => '1767ce88',
    'container.build_time' => 1754408111,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMknqzKG');
